(async function(){
  const S=VyroStore,C=VyroCatalog,root=document.getElementById('cartRoot');
  try{const data=await C.ready;await C.libraryReady;
    function render(){const ids=VyroCart.list(),totals={};if(!ids.length){root.innerHTML='<div class="empty-state"><h2>Your cart is empty</h2><p>Save products here to return to them later.</p><a class="btn btn-primary" href="shop.html">Explore VYRO</a></div>';return;}
      root.innerHTML='<div class="cart-layout"><div>'+ids.map(id=>{const p=data.products.find(p=>p.id===id);if(!p)return `<article class="cart-item"><p>This saved product is no longer available.</p><button class="btn btn-ghost" data-remove="${S.escape(id)}">Remove</button></article>`;if(!C.isFree(p)&&p.price_amount!=null)totals[p.currency]=(totals[p.currency]||0)+Number(p.price_amount);const free=C.isFree(p);
      return `<article class="cart-item"><a href="${C.productURL(p)}"><img src="${S.escape(S.safeURL(p.cover_path))}" alt="${S.escape(p.name)}" width="108" height="144" loading="lazy"></a><div><span class="badge">${C.availability(p)}</span><h2><a href="${C.productURL(p)}">${S.escape(p.name)}</a></h2><p>${S.escape(C.typeLabel(p))} · Quantity 1</p><div class="product-price-row">${C.priceHTML(p)}</div><div class="cart-item-actions">${free?`<button class="btn btn-primary btn-sm" data-buy="${S.escape(p.id)}">Download PDF</button>`:C.owned.has(p.id)?'<a class="btn btn-primary btn-sm" href="account.html">My Library</a>':`<button class="btn btn-primary btn-sm" data-buy="${S.escape(p.id)}" ${p.checkout_ready?'':'disabled'}>${p.checkout_ready?'Checkout this product':C.availability(p)}</button>`}<button class="btn btn-ghost btn-sm" data-remove="${S.escape(p.id)}" aria-label="Remove ${S.escape(p.name)}">Remove</button></div></div></article>`;}).join('')+'</div><aside class="cart-summary"><h2>Saved cart</h2><p>'+ids.length+' products</p><div class="cart-totals">'+(S.freeMode()?'<strong>Free access enabled</strong>':Object.entries(totals).map(([c,n])=>'<strong>'+S.escape(S.money(n,c))+'</strong>').join(''))+'</div><p>'+(S.freeMode()?'Payments are disabled in this release. Use the download button on any saved guide.':'Totals include saved products that may not be available yet. Final prices are checked before payment.')+'</p><button class="btn btn-secondary" id="clearCart">Clear saved cart</button></aside></div>';document.getElementById('clearCart').addEventListener('click',()=>VyroCart.clear());
    }window.addEventListener('vyro:cart',render);render();
  }catch{root.innerHTML='<p class="notice">We couldn’t load current product details. Your saved cart is still on this device. Please try again later.</p>';}
})();
