(function(){
  'use strict';
  const categories=[
    {id:'3b101b86-aaff-5e4f-a900-a5f01528bcb9',slug:'fitness',name:'Fitness',description:'Workouts, training programs, challenges and fitness guides.',display_order:0,active:true},
    {id:'9df2d10d-745a-5638-ac49-db4ef4cfc1fd',slug:'food-nutrition',name:'Food & Nutrition',description:'Recipes, meal plans, healthy food guides and nutrition resources.',display_order:10,active:true},
    {id:'e60a28a9-7eab-5382-ad34-a30e2a57b244',slug:'style',name:'Style',description:'Outfit guides, wardrobe ideas, styling resources and visual inspiration.',display_order:20,active:true},
    {id:'0c9fd239-7850-56ac-a837-c56b99a4d6d8',slug:'self-improvement',name:'Self-Improvement',description:'Habits, productivity, routines, personal development and lifestyle systems.',display_order:30,active:true}
  ];
  const products=[
    {id:'0813bd61-db13-5e18-a51d-87c515a75743',slug:'calisthenics-8week',name:'The 8-Week Calisthenics Starter System',category_id:categories[0].id,subcategory:'Calisthenics',product_type:'digital_file',status:'active',short_description:'A structured 8-week bodyweight program built for true beginners.',full_description:'The 8-Week Calisthenics Starter System takes you from basic movement practice into a repeatable three-day strength routine. It includes progression rules, weekly check-ins, recovery guidance and a printable tracker.',who_for:'Beginners who want a simple bodyweight plan they can follow at home or outdoors.',price_amount:24,compare_at_price:34,currency:'USD',cover_path:'calisthenics-cover.png',featured:true,bestseller:false,is_new:false,release_date:'2026-04-02',format:'PDF + printable tracker',pages_text:'10 pages',included_items:['8-week structured training calendar','Beginner exercise progression ladder','Weekly schedule with rest-day guidance','Printable progress tracker','Warm-up routine','Recovery and nutrition basics'],learning_points:['How to build strength without a gym','How to progress an exercise safely','How to structure a training week'],display_order:0,free_file:'free-products/calisthenics-8week.pdf'},
    {id:'cad9745a-0b1e-52a1-a833-b85d6947b739',slug:'high-protein-50',name:'50 High-Protein Recipes',category_id:categories[1].id,subcategory:'High Protein',product_type:'digital_file',status:'active',short_description:'50 simple, high-protein meals with estimated calories and protein.',full_description:'Fifty practical recipes across breakfast, lunch, dinner and snacks, designed for normal ingredients and normal weeknights. Each recipe includes estimated calories and protein plus a simple method.',who_for:'Anyone who wants realistic protein-focused meals without complicated cooking.',price_amount:19,compare_at_price:null,currency:'USD',cover_path:'food-cover.png',featured:true,bestseller:false,is_new:true,release_date:'2026-07-18',format:'PDF cookbook',pages_text:'14 pages',included_items:['50 recipes','Estimated calories and protein per recipe','Ingredient swaps','Weekly shopping template'],learning_points:['How to vary high-protein meals','How to batch-cook useful components','How to swap ingredients sensibly'],display_order:10,free_file:'free-products/high-protein-50.pdf'},
    {id:'ffe65fc7-3fd9-5b92-ae13-466b4c1df488',slug:'mens-style-guide',name:"The Ultimate Men's Style Guide",category_id:categories[2].id,subcategory:"Men's Style",product_type:'digital_file',status:'active',short_description:'Build a wardrobe that actually works together, for every occasion.',full_description:'A practical guide to fit, colour, outfit formulas and wardrobe essentials, with forty outfit combinations and a reusable wardrobe checklist.',who_for:'Anyone who wants to look put-together without spending hours second-guessing outfits.',price_amount:22,compare_at_price:29,currency:'USD',cover_path:'style-cover.png',featured:true,bestseller:false,is_new:false,release_date:'2026-02-10',format:'PDF guide',pages_text:'9 pages',included_items:['40 outfit combinations','Colour palette framework','Casual, smart-casual and formal formulas','Fit checkpoints','Wardrobe checklist'],learning_points:['How to combine colours with confidence','How to build outfits around core pieces','How to dress for different levels of formality'],display_order:20,free_file:'free-products/mens-style-guide.pdf'},
    {id:'2753ae5b-7313-5ec9-afa2-a16561c23176',slug:'habit-reset',name:'The Habit Reset Blueprint',category_id:categories[3].id,subcategory:'Habits',product_type:'digital_file',status:'active',short_description:'A 21-day framework for replacing bad habits with ones that stick.',full_description:'A focused workbook for identifying cues, redesigning the environment, creating a minimum habit and reviewing progress across three weeks.',who_for:'Anyone who has tried to build better habits before and wants a more realistic system.',price_amount:18,compare_at_price:null,currency:'USD',cover_path:'habit-cover.png',featured:true,bestseller:false,is_new:true,release_date:'2026-08-01',format:'PDF workbook',pages_text:'9 pages',included_items:['21-day habit reset framework','Habit-stacking worksheet','Environment audit','Weekly reviews','Relapse-recovery guide'],learning_points:['How to identify what drives a habit','How to design habits that survive a bad week','How to recover after missing days'],display_order:30,free_file:'free-products/habit-reset.pdf'},
    {id:'4793d166-04df-5001-a990-b74f709d4a73',slug:'home-workout-30',name:'30-Day Home Workout Challenge',category_id:categories[0].id,subcategory:'Challenges',product_type:'digital_file',status:'active',short_description:'30 short, no-equipment workouts you can do anywhere.',full_description:'Thirty days of short strength, conditioning, mobility and recovery sessions with easier options and a printable completion calendar.',who_for:'People who want a short, no-equipment routine they can start today.',price_amount:16,compare_at_price:22,currency:'USD',cover_path:'workout-cover.png',featured:false,bestseller:false,is_new:false,release_date:'2026-03-15',format:'PDF + calendar',pages_text:'10 pages',included_items:['30 daily sessions','Low-impact modifications','Movement key','Visual progress calendar'],learning_points:['How to stay consistent for 30 days','How to modify workouts to your level','How to continue after day 30'],display_order:40,free_file:'free-products/home-workout-30.pdf'},
    {id:'90c2d751-37ae-5fe1-a295-82ece6b242da',slug:'meal-prep-system',name:'The Weekly Meal Prep System',category_id:categories[1].id,subcategory:'Meal Plans',product_type:'digital_file',status:'active',short_description:'Plan, shop and prep a full week of meals in under two hours.',full_description:'A repeatable component-based meal-prep system with a 120-minute workflow, four rotating meal templates, storage guidance and printable planning sheets.',who_for:'Anyone tired of deciding what to eat every single day.',price_amount:21,compare_at_price:null,currency:'USD',cover_path:'meal-cover.png',featured:false,bestseller:false,is_new:true,release_date:'2026-08-20',format:'PDF + templates',pages_text:'9 pages',included_items:['4 rotating meal templates','Planning sheet','120-minute batch-cooking timeline','Storage and reheating guide','Shopping list template'],learning_points:['How to plan a week of meals quickly','How to batch-cook components efficiently','How to keep variety through the week'],display_order:50,free_file:'free-products/meal-prep-system.pdf'},
    {id:'d95f8f86-d6ad-59ce-a971-cee3dc34b306',slug:'womens-style-capsule',name:'The Capsule Wardrobe Guide',category_id:categories[2].id,subcategory:'Wardrobe',product_type:'digital_file',status:'active',short_description:'Build a versatile wardrobe from a small set of core pieces.',full_description:'A step-by-step capsule wardrobe guide covering closet auditing, core-piece selection, colour planning, outfit combinations and seasonal transitions.',who_for:'Anyone who wants a simpler, more versatile wardrobe without buying constantly.',price_amount:20,compare_at_price:null,currency:'USD',cover_path:'wardrobe-cover.png',featured:false,bestseller:false,is_new:false,release_date:'2026-01-22',format:'PDF guide',pages_text:'8 pages',included_items:['Core capsule checklist','Seasonal transition guide','30 outfit prompts','Closet audit worksheet','Buying filter'],learning_points:['How to choose versatile core pieces','How to transition a capsule between seasons','How to simplify an existing wardrobe'],display_order:60,free_file:'free-products/womens-style-capsule.pdf'},
    {id:'7370ddbb-7518-5b08-aebf-f5c1a095076d',slug:'deep-work-system',name:'The Deep Work Productivity System',category_id:categories[3].id,subcategory:'Productivity',product_type:'digital_file',status:'active',short_description:'A weekly planning system built around real, focused work.',full_description:'A reusable planning system for protecting deep-work blocks, batching shallow tasks, auditing distractions and reviewing a week based on completed outcomes.',who_for:'Anyone who feels busy all day but rarely finishes meaningful work.',price_amount:23,compare_at_price:27,currency:'USD',cover_path:'productivity-cover.png',featured:false,bestseller:false,is_new:false,release_date:'2026-05-05',format:'PDF + planner',pages_text:'9 pages',included_items:['Weekly outcome planner','Task-batching framework','Distraction audit worksheet','Focus-session tracker','Weekly review'],learning_points:['How to protect focused time','How to batch shallow tasks','How to reduce daily distractions'],display_order:70,free_file:'free-products/deep-work-system.pdf'}
  ];
  window.VYRO_STATIC_CATALOG={categories,products};
})();
