(async function(){
  const S=VyroStore,C=VyroCatalog,params=new URLSearchParams(location.search),state={category:params.get('category')||'all',q:params.get('q')||'',price:'all',sort:params.get('sort')||'newest',type:'all'},grid=document.getElementById('shopGrid'),count=document.getElementById('resultsCount');
  count.textContent='Loading products…';
  try{const data=await C.ready;await C.libraryReady;document.getElementById('shopSearch').value=state.q;const chips=document.getElementById('categoryChips');
    function render(){chips.innerHTML=[{slug:'all',name:'All products'},...data.categories].map(c=>`<button class="chip ${state.category===c.slug?'active':''}" data-cat="${S.escape(c.slug)}" aria-pressed="${state.category===c.slug}">${S.escape(c.name)}</button>`).join('');const cat=data.categories.find(c=>c.slug===state.category),ids=new Set(cat?[cat.id]:[]);for(let i=0;i<data.categories.length;i++)for(const c of data.categories)if(ids.has(c.parent_id))ids.add(c.id);
      let list=data.products.filter(p=>(state.category==='all'||ids.has(p.category_id))&&(state.type==='all'||p.product_type===state.type)&&(!state.q||[p.name,p.short_description,p.subcategory].join(' ').toLowerCase().includes(state.q.toLowerCase()))&&(state.price==='all'||(state.price==='under20'&&p.price_amount<20)||(state.price==='20to25'&&p.price_amount>=20&&p.price_amount<=25)||(state.price==='over25'&&p.price_amount>25)));
      if(state.sort==='newest')list.sort((a,b)=>new Date(b.release_date||b.created_at)-new Date(a.release_date||a.created_at));if(state.sort==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured)||a.display_order-b.display_order);if(state.sort.startsWith('price-'))list.sort((a,b)=>a.currency===b.currency?(a.price_amount-b.price_amount)*(state.sort==='price-asc'?1:-1):a.currency.localeCompare(b.currency));
      grid.innerHTML=list.map(C.card).join('');count.textContent=list.length+' '+(list.length===1?'product':'products');document.getElementById('emptyState').hidden=!!list.length;
      const u=new URL(location.href);if(state.category==='all')u.searchParams.delete('category');else u.searchParams.set('category',state.category);if(state.q)u.searchParams.set('q',state.q);else u.searchParams.delete('q');history.replaceState(null,'',u);
    }
    chips.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b){state.category=b.dataset.cat;render();}});for(const[id,k]of[['priceFilter','price'],['sortSelect','sort'],['typeFilter','type']])document.getElementById(id).addEventListener('change',e=>{state[k]=e.target.value;render();});document.getElementById('shopSearch').addEventListener('input',e=>{state.q=e.target.value.trim();render();});
    document.getElementById('clearFilters').addEventListener('click',()=>{Object.assign(state,{category:'all',q:'',price:'all',sort:'newest',type:'all'});document.getElementById('shopSearch').value='';for(const[id,k]of[['priceFilter','price'],['sortSelect','sort'],['typeFilter','type']])document.getElementById(id).value=state[k];render();});document.getElementById('sortSelect').value=['newest','featured','price-asc','price-desc'].includes(state.sort)?state.sort:'newest';render();
  }catch{count.textContent='The catalog is temporarily unavailable. Please try again later.';grid.innerHTML='';}
})();
